version: "3"

services:

  sonar-sever:
    image: "sonarqube:latest"
    container_name: "sonar-server"
    restart: unless-stopped
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    ports:
      - "9000:9000"
    networks:
      - casestudy

  redis-client:
    image: "redis"
    container_name: "redis_covidstat"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

    networks:
      - casestudy

  jenkins-server:
    build:
      dockerfile: Dockerfile-jenkinsserver
      context: .
    container_name: "jenkins_covidstat"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/jenkins-data:/var/jenkins_home
    user: root
    ports:
      - "8081:8080"
    networks:
      - casestudy

networks:
  casestudy:
    external: true

volumes:
  redis_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions: