FROM 'jenkins/jenkins:lts-jdk17'

USER root
RUN apt-get update
RUN apt-get install
RUN apt-get install docker.io -y

# Add the jenkins user to the docker group to allow socket access, to enable access
RUN usermod -aG docker jenkins

USER jenkins

